name: Deployment Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened,synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action
        with: 
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 #Esto tomará el último commit
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Deploy main
        if: ${{ github.event_name == 'push' }}
        run: echo 'App deployment successfully'
      - name: New change
        run: echo "New change"


